version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: bimasoft-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - bimasoft-network

  backend:
    user: node
    image: node:20
    container_name: bimasoft-backend
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "3000:3000"
    networks:
      - bimasoft-network
    command: npm start

networks:
  bimasoft-network:
    driver: bridge
