name: Deploy to Heroku

on:
  push:
    branches:
      - main # Change this if you use a different branch for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Adjust to your Node.js version

      - name: Install dependencies
        run: npm install # Or yarn install if using Yarn

      - name: Build the app (if needed)
        run: npm run build # Skip if not using TypeScript or a build step

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: false # Set to true if you're using a Docker container

      - name: Notify success
        if: success()
        run: echo "Deployment successful! 🚀"
